matrix:
  BOSUN_VERSION:
    - 0.6.0

build:
  test:
    image: golang:1.9-alpine
    commands:
      - cp -r . $GOPATH/src/bosun.org
      - cd ${GOPATH}/src/bosun.org/cmd/bosun
      - go test -v bosun.org/...

  build_bosun:
    image: golang:1.9-alpine
    commands:
      - cd ${GOPATH}/src/bosun.org/cmd/bosun
      - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o bosun -tags esv5

  build_scollector:
    image: golang:1.9-alpine
    commands:
      - cd ${GOPATH}/src/bosun.org/cmd/scollector
      - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o scollector -tags esv5

publish:
  sandbox_bosun:
    image: s3
    region: eu-west-1
    bucket: skyscanner-sandbox-skymetrics-deployment
    acl: bucket-owner-full-control
    access_key: $$SANDBOX_ACCESSKEY
    secret_key: $$SANDBOX_SECRETKEY
    source: /drone/src/bosun.org/cmd/bosun/bosun
    target: /artifacts/bosun/$$BRANCH/bosun
    when:
      branch: '!master'

  prod_bosun:
    image: s3
    region: eu-west-1
    bucket: skyscanner-prod-skymetrics-deploymentsupport
    acl: bucket-owner-full-control
    access_key: $$PROD_ACCESSKEY
    secret_key: $$PROD_SECRETKEY
    source: /drone/src/bosun.org/cmd/bosun/bosun
    target: /artifacts/bosun/$$BOSUN_VERSION/bosun
    when:
      branch: master

  sandbox_scollector:
    image: s3
    region: eu-west-1
    bucket: skyscanner-sandbox-skymetrics-deployment
    acl: bucket-owner-full-control
    access_key: $$SANDBOX_ACCESSKEY
    secret_key: $$SANDBOX_SECRETKEY
    source: /drone/src/bosun.org/cmd/scollector/scollector
    target: /artifacts/scollector/$$BRANCH/scollector
    when:
      branch: '!master'

  prod_scollector:
    image: s3
    region: eu-west-1
    bucket: skyscanner-prod-skymetrics-deploymentsupport
    acl: bucket-owner-full-control
    access_key: $$PROD_ACCESSKEY
    secret_key: $$PROD_SECRETKEY
    source: /drone/src/bosun.org/cmd/scollector/scollector
    target: /artifacts/scollector/$$BOSUN_VERSION/scollector
    when:
      branch: master
