build:
  image: golang:1.9.1
  commands:
    - cp -r . $GOPATH/src/bosun.org
    - git clone git@gitlab.skyscannertools.net:data-platform/toml-merge.git toml-merge
    - cd ${GOPATH}/src/bosun.org/cmd/bosun
    - go test -v bosun.org/...

publish:
  ecr:
    image: 325714046698.dkr.ecr.eu-west-1.amazonaws.com/drone-plugins/docker
    repo: data-platform/bosun-build
    tag:
    - latest
    - bosun-0.6.0.$$BUILD_NUMBER
    - 1.0.$$BUILD_NUMBER
    region: eu-west-1
    storage_driver: overlay
    create_repository: True
    when:
      branch: master
