build:
  test:
    image: golang:1.9-alpine
    commands:
      - cp -r . $GOPATH/src/bosun.org
      - cd ${GOPATH}/src/bosun.org/cmd/bosun
      - go test -v bosun.org/...

  build:
    image: golang:1.9-alpine
    commands:
      - cd ${GOPATH}/src/bosun.org/cmd/bosun
      - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o bosun -tags esv5

publish:
  sandbox:
    image: s3
    region: eu-west-1
    bucket: skyscanner-sandbox-skymetrics-deployment
    acl: bucket-owner-full-control
    access_key: $$SANDBOX_ACCESSKEY
    secret_key: $$SANDBOX_SECRETKEY
    source: /drone/src/bosun.org/cmd/bosun/bosun
    target: /artifacts/bosun/latest/bosun
    when:
      branch: '!master'

  prod:
    image: s3
    region: eu-west-1
    bucket: skyscanner-prod-skymetrics-deploymentsupport
    acl: bucket-owner-full-control
    access_key: $$PROD_ACCESSKEY
    secret_key: $$PROD_SECRETKEY
    source: /drone/src/bosun.org/cmd/bosun/bosun
    target: /artifacts/bosun/build-$$BUILD_NUMBER/bosun
    when:
      branch: master

  prod_latest:
    image: s3
    region: eu-west-1
    bucket: skyscanner-prod-skymetrics-deploymentsupport
    acl: bucket-owner-full-control
    access_key: $$PROD_ACCESSKEY
    secret_key: $$PROD_SECRETKEY
    source: /drone/src/bosun.org/cmd/bosun/bosun
    target: /artifacts/bosun/latest/bosun
    when:
      branch: master
