Executing (MSFT_DSCLocalConfigurationManager)->GetConfigurationStatus()
Method execution successful.
Out Parameters:[abstract]
class __PARAMETERS
{
	[Stream: DisableOverride ToSubClass, EmbeddedInstance("MSFT_DSCConfigurationStatus"): ToSubClass, Out, ID(1): DisableOverride ToInstance] MSFT_DSCConfigurationStatus configurationStatus[] = {
instance of MSFT_DSCConfigurationStatus
{
	DurationInSeconds = 0;
	Error = "Current configuration does not exist. Execute Start-DscConfiguration command with -Path parameter to specify a configuration file and create a current configuration first.";
	HostName = "HOSTNAME-VM";
	IPV4Addresses = {"1.2.3.4", "127.0.0.1"};
	IPV6Addresses = {"fe80::9aac:52eb:f6ca:a32b%3", "::2000:0:0:0", "::1", "::2000:0:0:0"};
	JobID = "{1D75864B-1451-11E5-8276-08002721727D}";
	LCMVersion = "2.0";
	Locale = "en-US";
	MACAddresses = {"28-09-35-11-42-8A", "00-00-00-00-00-00-00-E0"};
	MetaConfiguration = 
instance of MSFT_DSCMetaConfiguration
{
	AllowModuleOverwrite = FALSE;
	ConfigurationDownloadManagers = {};
	ConfigurationMode = "ApplyAndMonitor";
	ConfigurationModeFrequencyMins = 15;
	DebugMode = {"NONE"};
	LCMCompatibleVersions = {"1.0", "2.0"};
	LCMState = "Idle";
	LCMVersion = "2.0";
	RebootNodeIfNeeded = FALSE;
	RefreshFrequencyMins = 30;
	RefreshMode = "PUSH";
	ReportManagers = {};
	ResourceModuleManagers = {};
	StatusRetentionTimeInDays = 10;
};
	Mode = "PUSH";
	RebootRequested = FALSE;
	StartDate = "2015/06/16 13:57:13";
	Status = "Failure";
	Type = "ReadOnly";
}};
	[out] uint32 ReturnValue = 0;
};