version: "3"
services:
  redis:
    image: redis:6
    container_name: redis
    ports:
      - "6379:6379"
  opentsdb:
    build:
      context: ..
      dockerfile: docker/opentsdb.Dockerfile
    container_name: opentsdb
    restart: on-failure
    ports:
      - "4242:4242"
      - "16010:16010"
      - "16030:16030"
  bosun:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    depends_on:
      - redis
      - opentsdb
    container_name: bosun
    restart: always
    ports:
      - "8070:8070"
