name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - name: go
      run: |
        export GOPATH=$HOME
        mkdir ${GOPATH}/src/
        cd ${GOPATH}/src/ && git clone --depth 1 https://github.com/langerma/bosun.git bosun.org
        cd ${GOPATH}/src/bosun.org/cmd/bosun && go get
        cd ${GOPATH}/src/bosun.org/cmd/bosun && go build
